services:
  backend:
    image: ghcr.io/tyemirov/tauth:latest
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/tyemirov/ghttp:latest
    depends_on:
      - backend
    command: ["--directory", "/srv/mpr-ui", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./docker:/srv/mpr-ui:ro
    restart: unless-stopped
