services:
  backend:
    image: ghcr.io/tyemirov/tauth:latest
    env_file:
      - ./.env
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/tyemirov/ghttp:latest
    depends_on:
      - backend
    command: ["--directory", "/srv/mpr-ui", "3000"]
    ports:
      - "3000:3000"
    volumes:
      - ./docker:/srv/mpr-ui:ro
