services:
  frontend:
    profiles:
      - tauth
    image: ghcr.io/tyemirov/ghttp:latest
    pull_policy: always
    depends_on:
      tauth:
        condition: service_started
    env_file:
      - ./demo/.env.ghttp
    ports:
      - "8000:8000"
    volumes:
      - ./demo/:/app/demo
      - ./demo/tauth-demo.html:/app/demo/index.html:ro
      - ./mpr-ui.css:/app/demo/mpr-ui.css:ro
      - ./mpr-ui.js:/app/demo/mpr-ui.js:ro
    restart: unless-stopped

  frontend-standalone:
    profiles:
      - tauth-standalone
    image: ghcr.io/tyemirov/ghttp:latest
    pull_policy: always
    depends_on:
      tauth:
        condition: service_started
    env_file:
      - ./demo/.env.ghttp
    ports:
      - "4443:8443"
    volumes:
      - ./demo/:/app/demo
      - ./demo/standalone.html:/app/demo/index.html:ro
      - ./mpr-ui.css:/app/demo/mpr-ui.css:ro
      - ./mpr-ui.js:/app/demo/mpr-ui.js:ro
      - /media/share/Drive/exchange/certs/computercat/computercat-cert.pem:/certs/cert.pem:ro
      - /media/share/Drive/exchange/certs/computercat/computercat-key.pem:/certs/key.pem:ro
    restart: unless-stopped

  tauth:
    profiles:
      - tauth
      - tauth-standalone
    image: ghcr.io/tyemirov/tauth:latest
    pull_policy: always
    env_file:
      - ./demo/.env.tauth
    ports:
      - "8080:8080"
    volumes:
      - tauth_data:/data
      - ./demo/tauth-config.yaml:/config.yaml:ro
    restart: unless-stopped

volumes:
  tauth_data:
