server:
  listen_addr: "${TAUTH_LISTEN_ADDR}"
  database_url: "${TAUTH_DATABASE_URL}"
  enable_cors: "${TAUTH_ENABLE_CORS}"
  cors_allowed_origins:
    - "${TAUTH_CORS_ORIGIN_1}"
    - "${TAUTH_CORS_ORIGIN_2}"
    - "${TAUTH_CORS_ORIGIN_3}"
  cors_allowed_origin_exceptions:
    - "${TAUTH_CORS_EXCEPTION_1}"
  enable_tenant_header_override: ${TAUTH_ENABLE_TENANT_HEADER_OVERRIDE}

tenants:
  - id: ${TAUTH_TENANT_ID_1}
    display_name: "MPR UI Demo"
    tenant_origins:
      - "${TAUTH_CORS_ORIGIN_1}"
      - "${TAUTH_CORS_ORIGIN_2}"
    google_web_client_id: "${TAUTH_GOOGLE_WEB_CLIENT_ID}"
    jwt_signing_key: "${TAUTH_JWT_SIGNING_KEY}"
    cookie_domain: ""
    session_cookie_name: "app_session"
    refresh_cookie_name: "app_refresh"
    session_ttl: "30m"
    refresh_ttl: "720h"
    nonce_ttl: "10m"
    allow_insecure_http: "${TAUTH_ALLOW_INSECURE_HTTP}"
